version: 1.0.{build}
image:
- Visual Studio 2017
- Ubuntu
build_script:
- ps: ./windows.bootstrap.ps1
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
  - sh: /bin/bash ./scripts/install-python.sh && source ~/.bashrc && pyenv install 3.7.0 && source ~/.bashrc && /bin/bash ubuntu.bootstrap.sh