ssh: {}
hotkeys: {}
terminal:
  shell: wsl
  autoOpen: true
  altIsMeta: false
  cursor: beam
  colorScheme:
    name: Chalkboard
    foreground: '#d9e6f2'
    background: '#29262f'
    cursor: '#d9e6f2'
    colors:
      - '#000000'
      - '#c37372'
      - '#72c373'
      - '#c2c372'
      - '#7372c3'
      - '#c372c2'
      - '#72c2c3'
      - '#d9d9d9'
      - '#323232'
      - '#dbaaaa'
      - '#aadbaa'
      - '#dadbaa'
      - '#aaaadb'
      - '#dbaada'
      - '#aadadb'
      - '#ffffff'
  ligatures: true
appearance:
  frame: thin
  dock: 'off'
