---
- name: Install python
  hosts: localhost
  tasks:

    - name: 'Update apt'
      apt:
        update_cache: yes
      become: yes
      tags:
        - ubuntu

    - name: 'Install pyenv prerequisites: {{packages}}'
      apt:
        name: '{{packages}}'
      vars:
        packages:
        - make
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - curl
        - llvm
        - libncurses5-dev
        - libncursesw5-dev
        - xz-utils
        - tk-dev
        - libffi-dev
      tags:
        - ubuntu

    - name: Clone pyenv repo
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest:  "{{ ansible_env.HOME }}/.pyenv"
      tags:
        - ubuntu

    # - name: Clone pyenv-virtualenv repo
    #   git:
    #     repo: https://github.com/yyuu/pyenv-virtualenv.git
    #     dest:  "{{ ansible_env.HOME }}/.pyenv/plugins/pyenv-virtualenv"

    - name: Clone pyenv-install-latest repo
      git:
        repo: https://github.com/momo-lab/pyenv-install-latest.git
        dest:  "{{ ansible_env.HOME }}/.pyenv/plugins/pyenv-install-latest"
      tags:
        - ubuntu

    - name: Put pyenv in PATH
      lineinfile:
        dest:  "{{ ansible_env.HOME }}/.bashrc"
        create: yes
        line: "{{ item }}"
        state: present
      with_items:
        - 'export PYENV_ROOT="$HOME/.pyenv"'
        - 'export PATH="$PYENV_ROOT/bin:$PATH"'
        - 'export PATH="$HOME/.pyenv/shims:$PATH"'
        - 'eval "$(pyenv init -)"'
      tags:
        - ubuntu

    # - name: Install latest 2.7 python # some path error: "pyenv: no such command 'install-latest'"
    #   shell: "source {{ ansible_env.HOME }}/.bashrc && {{ ansible_env.HOME }}/.pyenv/bin/pyenv install-latest 2.7"
    #   args:
    #     executable: /bin/bash
    #   become: yes
    #   tags:
    #     - always

    - name: Install python 2.7.15
      shell: "source {{ ansible_env.HOME }}/.bashrc && {{ ansible_env.HOME }}/.pyenv/bin/pyenv install 2.7.15"
      args:
        executable: /bin/bash
      become: yes
      tags:
        - always

    - name: Verify python installation
      shell: python --version
      tags:
        - always